#ifndef UTILS_H
#define UTILS_H

#define PAGE_LOGIN 0
#define PAGE_HOME 1
#define PAGE_REGISERT 2
#define PAGE_RESETPASSWD 3

#define PAGE_USERINFO_USER 1
#define PAGE_USERINFO_ADMIN 2
#define PAGE_DEVICE_USER 3
#define PAGE_DEVICE_ADMIN 4
#define PAGE_DATA_USER 5
#define PAGE_DATA_ADMIN 6
#define PAGE_ALARM_USER 7
#define PAGE_ALARM_ADMIN 8

#endif // UTILS_H
